### PR TITLE
Change version string for arduplane "ArduPlane V3.8.4-Yonah-LightwareI2C-Joseph"

### PR DESCRIPTION
**Pull request by ghost**
Updated version string to include new member's name (Joseph)

### CODE REVIEW

**Comment by disgruntled-patzer** [comment]
Oh man, I see that doing force-push didn't remove the old github commit (0f6a14759cf2afce0fef95b4208ac19817b094be) after all ):

My apologies Joseph, looks like you will need to follow the instructions that Ram set for Zhen Lee over here: https://github.com/yonahbox/ardupilot/pull/3

That way you will be able to get one single commit in the pull request and that makes things less messy (:

**Comment by disgruntled-patzer** [comment]
Also, regarding the commit title (file name followed by commit description), I see you were trying to follow the same title of my PR back then; actually my original commit title was in the wrong format (no file name); I tried to amend it but some problems came up so we had to remove the amended commit.

I'll see if I can try to amend the title of my commit (it requires the interactive git-rebase if I'm not wrong).

**Comment by ghost** [comment]
Oh i did not force push. I pulled the wrong version string onto my local machine, then corrected the merge issues using VS and then recommitted. After that i pushed it back to my fork. I saw this on one of the tutorial videos

**Comment by disgruntled-patzer** [comment]
Ok the original commit title has been modified, refer to cbaeb2559e5f23d7141e0ef727d6a387620ac663 for the new format (file name followed by description)

Also, I think it might be possible to use the git interactive rebase (git rebase -i) to combine those three commits in your pull request into one to make it "cleaner". But it will need a bit of manipulating (e.g. pulling these commits into your local repo before "squashing" them, then finding a way to delete the three original commits on github before pushing the new "squashed" commit).

You can try playing around with the git interactive rebase and see whether it works; instructions on how to use it are here (refer to "squashing commits"): https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History.

Just take note that for the "git rebase -i HEAD 3" which they use in the website, replace the HEAD-3 with the hash of the commit which is ONE STEP BEFORE the commit you want to edit. (Edit: Actually, HEAD 3 does work; just replace "3" with "n" which refers to the last "n" commits in your git log)

Otherwise, the safer way is to follow the method that Ram suggested for Zhen Lee.

All the best!

Edit: Oops, I didn't see your comment above. I think once we have already pushed "incorrect" commits into github, trying to remove them (to make the commit history look "cleaner") would still have to require some form of force pushing, but I might be mistaken.

@frizensami is there a way to resolve this without using force push?

**Comment by ghost** [comment]
im following Ram's method but having trouble connecting to remote repo for some weird reason. Im gonna try to correct this problem tomorrow

**Pull request closed without merging**
